# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  
  config.vm.define "controller" do |machine|
    # Management network for managing the host
    machine.vm.network :private_network, ip: "10.1.1.2",
                       :netmask => "255.255.0.0"
    machine.vm.network :private_network, ip: "10.1.0.2",
                       :netmask => "255.255.0.0"
    machine.vm.network :private_network, ip: "10.2.0.2",
                       :netmask => "255.255.0.0"
    machine.vm.network :private_network, ip: "10.3.0.2",
                       :netmask => "255.255.0.0"
    machine.vm.network :private_network, ip: "10.4.0.2",
                       :netmask => "255.255.0.0"
    machine.vm.network :private_network, ip: "10.5.0.2",
                       :netmask => "255.255.0.0"
    machine.vm.network :private_network, ip: "10.6.0.2",
                       :netmask => "255.255.0.0"
    machine.vm.hostname = "controller"
    machine.vm.provider :virtualbox do |v| 
      v.customize ["modifyvm", :id, "--memory", 1536]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end

end
